### ISSUE TITLE
More features from the Advanced settings of Google image search

### ISSUE THREAD

**Issue by MBtech** [teracow/googliser#43] opened 2019-10-29 07:57 UTC
What do you think about adding more features from the advanced search settings of google image search? 
I think it could be useful to have following options:
1) Domains or sites to search the images from
2) Exclusion phrases
3) Safe search on/off 
4) Specifying preferred colours in the image

**Comment by teracow** [comment] 2019-10-29 08:22
Agree on options 1 & 2. Multiple domains and phrases?

Option 3 is easy enough to add (as a true/false option).

Option 4 is along the lines of something I've been considering for a while. I've been pondering adding support for custom "template files" the operator can configure themselves. The problem is the layout (and colours) of the gallery image is written as several command lines. If the operator wrote their own and messed-up, googliser might crash when trying to execute them. 

Thoughts?

**Comment by MBtech** [comment] 2019-10-29 09:53
I think users can specify multiple domain and phrases as comma separated values. Though I think through command line it will get a little messy and commands that are too long. Perhaps a configuration file with advanced configurations provided to the script would work better in that case. 

As for the colour I actually meant the advanced search feature that allows users to search for images with particular colours in them (well a limited set atleast). Such as colored images, black and white, transparent or a small list of colors that google provides.

**Comment by teracow** [comment] 2019-10-29 20:35
I agree with the configuration file option. 

Oh, colours in the search image? My bad. Yes, we could add those too. :)

**Comment by MBtech** [comment] 2019-10-30 07:54
What kind of configuration format do you think would be better:
JSON, 
YAML, 
ini, 
simple text files of the format `variable_name=value`?
I think the last option might be the cleanest for this case since we might just do `source config_file` to load variables. 
Unless there might be some hierarchical structure to the configuration variables and then one of the other formats might be more appropriate.
Any other ideas?

**Comment by teracow** [comment] 2019-10-30 08:12
I have no preference, it's entirely up-to you. Whichever format you use, you'll probably need to write your own read/write functions. :)

I don't know if a format supporting hierarchies is required for those options mentioned earlier, so you might get away with a flat `name=value` system. I used [this](https://github.com/brbsix/bash-config) a while back - it works fine.

Or, if you choose YAML, there's [this](https://medium.com/@mike.reider/handle-bash-config-file-variables-like-a-pro-957dc9a838ed).

**Comment by teracow** [comment] 2019-11-02 05:57
update: a search colour can now be specified via `--colour` or `--color`: https://github.com/teracow/googliser/commit/56952d8bb27c42f7c9fc0658f55b0b504171507e

**Comment by teracow** [comment] 2019-11-02 08:11
@MBtech my apologies, I should have asked and be coordinating better. Are you able to code options 1 and 2 as per your original request?

I'm working on option 3 right now.

**Comment by teracow** [comment] 2019-11-02 08:39
update: SafeSearch is now enabled by default and can be disabled with `--no-safesearch`: https://github.com/teracow/googliser/commit/51f5bfec0258c0456705865b9f9204317da14b77

**Comment by MBtech** [comment] 2019-11-02 11:29
I have a deadline in 2 days so I am working on that. But I will do 1 and 2 after that. Or perhaps even before, if I get some time in the meantime.

**Comment by teracow** [comment] 2019-11-04 05:27
@MBtech apologies for all the major commits lately, I realise it can't be easy trying to add to code that keeps changing. 

Hopefully, the major stuff is now out of the way, and things will settle-down a bit. :)

**Comment by teracow** [comment] 2019-11-07 19:24
Hi @MBtech I've just tried a regular search (no excluded phrases or specific sites), and found that if I search for a phrase that has whitespace e.g. 'big green car', only a search for 'big' is performed. It seems to be breaking on white-space. Can you please check this out? Thank you.

**Comment by MBtech** [comment] 2019-11-08 00:04
Ahh let me check what's going on

**Comment by MBtech** [comment] 2019-11-08 00:29
I think it's fixed now. It was because I missed the quotes while passing the phrase to the finalize function

**Comment by teracow** [comment] 2019-11-08 01:12
Yup, looks fine now. Nice work. :)

**Comment by MBtech** [comment] 2019-11-08 02:54
I think we can close this issue now.

**Comment by teracow** [comment] 2019-11-08 03:13
Are you able to update the readme? 

Also, do you have any plans to support options 1 and 2 via input files? 

Yes, closure is fine, whenever you're happy the issue has been resolved.

**Comment by MBtech** [comment] 2019-11-08 07:20
Readme has been updated. 
For the files I was actually simply thinking of a bash variable file that we could simply import the variables from using `source`. I wasn't thinking about something specific to option 1 and 2 but something in general. So that any variable that is defined within the script could be specified as in the config file and simply imported without doing all that much and variables passed from command line could get a preference. 
What do you think?

**Comment by teracow** [comment] 2019-11-08 07:34
Sounds good. :)
Maybe the user could just specify their file in-place of the word/site list like:
```
./googliser.sh --exclude-words "$(<exclusion-words.txt)"
```
or similar? That's already supported in BASH and only requires the word/site list files to be correctly formatted.

**Comment by teracow** [comment] 2019-11-10 05:15
@MBtech I've closed this, unless you'd like to reopen it (which you're welcome to do). :)

**Closed as completed** 2019-11-10 05:14 UTC
Labels: enhancement, work-in-progress

**Comment by MBtech** [comment] 2019-11-10 06:54
That's fine by me. That example that you gave can be added to the readme perhaps. Or may be there is a need to have a wiki. So that perhaps additional example, especially for advanced options can be moved there. That would shorten the readme a little so that it's fast to get started and more details are available for those users who want more control.

**Comment by teracow** [comment] 2019-11-10 07:01
Good idea. Would you be interested in creating and maintaining a wiki for googliser?

**Comment by MBtech** [comment] 2019-11-10 07:53
Sure. I can help with that.

**Comment by teracow** [comment] 2019-11-10 08:12
Cool, I've just created a collaborator invite for your account . I'm guessing GitHub emails it to you.

**Comment by teracow** [comment] 2019-11-10 08:14
If it doesn't, please use this link: https://github.com/teracow/googliser/invitations

**Comment by MBtech** [comment] 2019-11-10 09:03
Yup got it. I will setup the wiki and then anything that's not really important can be removed from the readme, after we are happy with the way wiki looks.

**Comment by teracow** [comment] 2019-11-10 09:05
That's great! Appreciate you taking this on. :)

I think you should be OK to edit the wiki now. If it's not working, please let me know. I'm kinda new to this.
